import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from "axios";
import { useState, useEffect } from 'react';

export default function Home() {
  const [add, setAdd] = useState([]);
  const [address, setAddress] = useState()

 


  // useEffect(() => {
  //   handleAddress();
  // }, [address]);

  const handleAddress = async () => {
    const resp = await axios.get(
      `https://api.covalenthq.com/v1/1/address/${address}/balances_v2/`,
      { auth: { username: "ckey_13efa795783c4edd9b5991290d7" } },
    );
    setAdd(resp.data.data.address !== null ? resp.data.data.items : null );
    
  };
  

 return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <div className={styles.footer}>
        <input onChange={(e) => setAddress(e.target.value)}></input>
        <button onClick={handleAddress}>Get Tokens</button>
        </div>
        <div className={styles.custom}>
        {add?.map((items, address )=> (
          <div className={styles.grid} key={items.address}>
            <h3>{items.contract_name}</h3>
          <div> Blalance: {(items.balance)/(10 ** items.contract_decimals)}{' '} {items.contract_ticker_symbol} </div>
          <p>Quote Rate:{items.quote_rate}</p>
          <p>Quote Rate(Day):{items.quote_rate_24h}</p>
          <p> Worth in USD: {items.quote}</p>
          <Image height={5} width={5} alt='logo' src={items.logo_url}></Image>
          </div>
        ))}
        </div>
      
    </div>
  )
}
